### ISSUE TITLE
Second example of chapter 13 does not work

### ISSUE THREAD

**Issue by HelgeCPH** [andrewlock/asp-dot-net-core-in-action-3e#1]
Hej, I am trying to understand why the second example of chapter 13 (https://github.com/andrewlock/asp-dot-net-core-in-action-3e/tree/main/Chapter13/B_ATypicalRazorPage/ATypicalRazorPage) is not working for me as expected.

I would expect that after cloning this repository, changing directory to the second example of chapter 13 (`cd asp-dot-net-core-in-action-3e/Chapter13/B_ATypicalRazorPage/ATypicalRazorPage/`), and finally running `dotnet run`, that an HTTP GET request to http://localhost:5043/Simple would return an HTML page containing something like 

  > ToDo items:
  >   * Bread
  >   * Milk
  >   * Get gas

However, the response contains an empty HTML body and the head of the HTML page is not the one set in asp-dot-net-core-in-action-3e/Chapter13/B_ATypicalRazorPage/ATypicalRazorPage/Pages/Category.cshtml.cs.

To me it seems that something with routing is going wrong since the page and its model never seem to be initialized.
Could you please point me to a possible cause? Then I can try to send a fix with a PR.

Thank you in advance for your help.

**Comment by andrewlock** [comment]
Hi @HelgeCPH!

The page you're trying to open `/Simple` does not exist, so you are getting a `404` result from the browser. 

Inside the Razor Page you have the following directive:

```csharp
@page "{category}"
```

which means "_add_ the `{category}` segment to the page's default route template". As this is the `Category.cshml` page, the default route is `Category`, which gives a complete route of `Category/{category}`. In other words, if you browse to http://localhost:5043/Category/Simple your page should work 🙂 

If you were building an app, and you _didn't_ want the `Category/` prefix, you could use the following in your Razor Page:

```csharp
@page "/{category}"
```

Note the initial `/` which means "ignore any 'default' segments".

I hope that helps, let me know if you have any other issues!

Thanks for reading and trying it out! 😃

**Comment by HelgeCPH** [comment]
Hej Andrew, thank you for the super quick answer! Your solution above is correct and works. That is, I forgot to add `Category` to the URL before the segment that will get passed as parameter to the handler... Thank you very much for the hint and also the tip with the leading slash.

In case others stumble upon this issue: I should have read on to chapter 13.4.1 in the book, where the respective routes are given :)
